Fix directory creation failure
I installed this module on a fresh boxen install, and /opt/boxen/homebrew/lib does not exist.  This rewrite should ensure its creation if it is not already there.

Error: Cannot create /opt/boxen/homebrew/lib/python2.7; parent directory /opt/boxen/homebrew/lib does not exist
Error: /Stage[main]/Python/File[/opt/boxen/homebrew/lib/python2.7]/ensure: change from absent to directory failed: Cannot create /opt/boxen/homebrew/lib/python2.7; parent directory /opt/boxen/homebrew/lib does not exist